DROP TABLE `broadcast_channels`;--> statement-breakpoint
DROP TABLE `bundles`;--> statement-breakpoint
DROP TABLE `creative_assets`;--> statement-breakpoint
DROP TABLE `creator_availability`;--> statement-breakpoint
DROP TABLE `dispute_timeline`;--> statement-breakpoint
DROP TABLE `escalations`;--> statement-breakpoint
DROP TABLE `evidence_packs`;--> statement-breakpoint
DROP TABLE `executive_metrics`;--> statement-breakpoint
DROP TABLE `fraud_scores`;--> statement-breakpoint
DROP TABLE `hooks_library`;--> statement-breakpoint
DROP TABLE `idempotency_keys`;--> statement-breakpoint
DROP TABLE `inventory_lots`;--> statement-breakpoint
DROP TABLE `launch_checklists`;--> statement-breakpoint
DROP TABLE `live_highlights`;--> statement-breakpoint
DROP TABLE `live_price_drops`;--> statement-breakpoint
DROP TABLE `live_show_segments`;--> statement-breakpoint
DROP TABLE `lsn_disputes`;--> statement-breakpoint
DROP TABLE `payout_holds`;--> statement-breakpoint
DROP TABLE `policy_incidents`;--> statement-breakpoint
DROP TABLE `price_book_entries`;--> statement-breakpoint
DROP TABLE `price_books`;--> statement-breakpoint
DROP TABLE `promotions`;--> statement-breakpoint
DROP TABLE `provider_transactions`;--> statement-breakpoint
DROP TABLE `provider_webhook_dedup`;--> statement-breakpoint
DROP TABLE `receiving_workflows`;--> statement-breakpoint
DROP TABLE `reconciliation_discrepancies`;--> statement-breakpoint
DROP TABLE `refund_policies`;--> statement-breakpoint
DROP TABLE `region_configs`;--> statement-breakpoint
DROP TABLE `regional_inventory`;--> statement-breakpoint
DROP TABLE `regression_seeds`;--> statement-breakpoint
DROP TABLE `return_requests`;--> statement-breakpoint
DROP TABLE `schedule_slots`;--> statement-breakpoint
DROP TABLE `sku_kill_rules`;--> statement-breakpoint
DROP TABLE `sku_profitability`;--> statement-breakpoint
DROP TABLE `supplier_contacts`;--> statement-breakpoint
DROP TABLE `supplier_contracts`;--> statement-breakpoint
DROP TABLE `supplier_performance`;--> statement-breakpoint
DROP TABLE `supplier_samples`;--> statement-breakpoint
DROP TABLE `third_party_logistics_providers`;--> statement-breakpoint
DROP TABLE `third_party_shipments`;--> statement-breakpoint
DROP TABLE `third_party_tracking_events`;--> statement-breakpoint
DROP TABLE `top_performers`;--> statement-breakpoint
DROP TABLE `trend_spotting`;--> statement-breakpoint
DROP TABLE `ugc_briefs`;